-- Sysadmin POC - Entity Definitions
-- Each entity is cloned from a vanilla entity that provides the needed functionality
-- Custom sprites are generated by scripts/generate-sprites.py

-- Sprite path helper
local sprite_path = "__sysadmin-poc__/graphics/entity/"

-- Data Sensor - Clone iron chest (container type)
-- Purpose: Collects data packets from nearby assemblers into its inventory
-- Why container: Needs inventory to store generated data packets, supports inserter interaction
-- Circuit-connectable: Can read IT control signals to enable/disable monitored assemblers
local sensor = table.deepcopy(data.raw["container"]["iron-chest"])
sensor.name = "data-sensor"
sensor.icon = "__sysadmin-poc__/graphics/icons/data-sensor.png"
sensor.icon_size = 32
sensor.minable.result = "data-sensor"
sensor.inventory_size = 4  -- Small buffer for data packets
sensor.localised_name = {"entity-name.data-sensor"}
sensor.localised_description = {"entity-description.data-sensor"}
-- Enable circuit connections for reading control signals
-- Iron chest already has circuit connector defined, just extend the wire distance
sensor.circuit_wire_max_distance = 9
-- Use custom sprite
sensor.picture = {
  layers = {
    {
      filename = sprite_path .. "data-sensor.png",
      priority = "extra-high",
      width = 64,
      height = 64,
      shift = {0, 0},
      scale = 0.5
    },
    {
      filename = sprite_path .. "data-sensor-shadow.png",
      priority = "extra-high",
      width = 64,
      height = 64,
      shift = {0, 0},
      scale = 0.5,
      draw_as_shadow = true
    }
  }
}
data:extend({sensor})

-- Sensor Circuit Interface - Hidden constant combinator for per-sensor signal output
-- This entity is automatically placed when a sensor is built and outputs the sensor's metrics
-- It overlays the sensor position and shares circuit connections
local sensor_interface = table.deepcopy(data.raw["constant-combinator"]["constant-combinator"])
sensor_interface.name = "sensor-circuit-interface"
sensor_interface.icon = "__sysadmin-poc__/graphics/icons/data-sensor.png"  -- Shares sensor icon
sensor_interface.icon_size = 32
sensor_interface.localised_name = {"entity-name.sensor-circuit-interface"}
sensor_interface.localised_description = {"entity-description.sensor-circuit-interface"}
-- Make it non-selectable and non-mineable (managed by sensor)
sensor_interface.flags = {"not-blueprintable", "not-deconstructable", "placeable-off-grid", "not-on-map", "hide-alt-info"}
sensor_interface.selectable_in_game = false
sensor_interface.collision_mask = {layers = {}}  -- No collision
sensor_interface.minable = nil
-- Match sensor position and circuit reach
sensor_interface.circuit_wire_max_distance = 9
-- Small collision box that doesn't interfere
sensor_interface.collision_box = {{0, 0}, {0, 0}}
sensor_interface.selection_box = {{0, 0}, {0, 0}}
-- Use invisible sprites (we don't want to see it)
sensor_interface.sprites = {
  north = {
    layers = {{
      filename = "__core__/graphics/empty.png",
      width = 1,
      height = 1,
      priority = "low"
    }}
  },
  east = {
    layers = {{
      filename = "__core__/graphics/empty.png",
      width = 1,
      height = 1,
      priority = "low"
    }}
  },
  south = {
    layers = {{
      filename = "__core__/graphics/empty.png",
      width = 1,
      height = 1,
      priority = "low"
    }}
  },
  west = {
    layers = {{
      filename = "__core__/graphics/empty.png",
      width = 1,
      height = 1,
      priority = "low"
    }}
  }
}
data:extend({sensor_interface})

-- Network Cable - Clone transport belt
-- Purpose: Moves data packets from sensors to servers
-- Uses maximum belt speed for instant data flow feel
-- Visual: Black tint on belt, orange data packets remain visible
-- Note: Belt animations use vanilla sprites with dark tint applied
local cable = table.deepcopy(data.raw["transport-belt"]["transport-belt"])
cable.name = "network-cable"
cable.icon = "__sysadmin-poc__/graphics/icons/network-cable.png"
cable.icon_size = 32
cable.minable.result = "network-cable"
cable.next_upgrade = nil  -- No upgrade path in POC
cable.speed = 1.0  -- Maximum speed (faster than express, works with auto-transfer)
cable.localised_name = {"entity-name.network-cable"}
cable.localised_description = {"entity-description.network-cable"}
-- Apply dark tint to belt animations (items render separately, stay colored)
local dark_tint = {r = 0.15, g = 0.15, b = 0.15, a = 1}
cable.belt_animation_set.animation_set.tint = dark_tint
if cable.belt_animation_set.ending_patch then
  cable.belt_animation_set.ending_patch.sheet.tint = dark_tint
end
data:extend({cable})

-- Network Cable Underground - Clone underground belt
-- Purpose: Underground data transmission
local cable_underground = table.deepcopy(data.raw["underground-belt"]["underground-belt"])
cable_underground.name = "network-cable-underground"
cable_underground.icon = "__sysadmin-poc__/graphics/icons/network-cable-underground.png"
cable_underground.icon_size = 32
cable_underground.minable.result = "network-cable-underground"
cable_underground.max_distance = 10  -- Standard underground distance
cable_underground.speed = 1.0  -- Match cable speed
cable_underground.localised_name = {"entity-name.network-cable-underground"}
cable_underground.localised_description = {"entity-description.network-cable-underground"}
-- Apply dark tint
cable_underground.belt_animation_set.animation_set.tint = dark_tint
if cable_underground.belt_animation_set.ending_patch then
  cable_underground.belt_animation_set.ending_patch.sheet.tint = dark_tint
end
if cable_underground.structure then
  if cable_underground.structure.direction_in then
    cable_underground.structure.direction_in.sheet.tint = dark_tint
  end
  if cable_underground.structure.direction_out then
    cable_underground.structure.direction_out.sheet.tint = dark_tint
  end
  if cable_underground.structure.direction_in_side_loading then
    cable_underground.structure.direction_in_side_loading.sheet.tint = dark_tint
  end
  if cable_underground.structure.direction_out_side_loading then
    cable_underground.structure.direction_out_side_loading.sheet.tint = dark_tint
  end
end
data:extend({cable_underground})

-- Network Cable Splitter - Clone splitter
-- Purpose: Split/merge data packet streams
local cable_splitter = table.deepcopy(data.raw["splitter"]["splitter"])
cable_splitter.name = "network-cable-splitter"
cable_splitter.icon = "__sysadmin-poc__/graphics/icons/network-cable-splitter.png"
cable_splitter.icon_size = 32
cable_splitter.minable.result = "network-cable-splitter"
cable_splitter.speed = 1.0  -- Match cable speed
cable_splitter.localised_name = {"entity-name.network-cable-splitter"}
cable_splitter.localised_description = {"entity-description.network-cable-splitter"}
-- Apply dark tint to splitter
cable_splitter.belt_animation_set.animation_set.tint = dark_tint
if cable_splitter.structure then
  if cable_splitter.structure.north then cable_splitter.structure.north.tint = dark_tint end
  if cable_splitter.structure.east then cable_splitter.structure.east.tint = dark_tint end
  if cable_splitter.structure.south then cable_splitter.structure.south.tint = dark_tint end
  if cable_splitter.structure.west then cable_splitter.structure.west.tint = dark_tint end
end
if cable_splitter.structure_patch then
  if cable_splitter.structure_patch.north then cable_splitter.structure_patch.north.tint = dark_tint end
  if cable_splitter.structure_patch.east then cable_splitter.structure_patch.east.tint = dark_tint end
  if cable_splitter.structure_patch.south then cable_splitter.structure_patch.south.tint = dark_tint end
  if cable_splitter.structure_patch.west then cable_splitter.structure_patch.west.tint = dark_tint end
end
data:extend({cable_splitter})

-- Recipe category for data processing
data:extend({
  {
    type = "recipe-category",
    name = "data-processing"
  }
})

-- Basic Server - Clone assembling machine 1
-- Purpose: Processes data packets (consumes them via crafting)
-- Why assembler: Has crafting capability, power requirements, inserter interaction
local server = table.deepcopy(data.raw["assembling-machine"]["assembling-machine-1"])
server.name = "basic-server"
server.icon = "__sysadmin-poc__/graphics/icons/basic-server.png"
server.icon_size = 32
server.minable.result = "basic-server"
server.crafting_categories = {"data-processing"}
server.crafting_speed = 1
server.energy_usage = "200kW"
server.localised_name = {"entity-name.basic-server"}
server.localised_description = {"entity-description.basic-server"}
-- Make it 1x1 instead of 3x3
server.collision_box = {{-0.35, -0.35}, {0.35, 0.35}}
server.selection_box = {{-0.5, -0.5}, {0.5, 0.5}}
server.drawing_box = {{-0.5, -0.5}, {0.5, 0.5}}
-- Set fixed recipe so it auto-processes data packets
server.fixed_recipe = "process-data"
-- Upgrade path: basic → advanced → hp
server.next_upgrade = "advanced-server"
server.fast_replaceable_group = "server"
-- Use custom sprite for the server graphics
server.graphics_set = {
  animation = {
    layers = {
      {
        filename = sprite_path .. "basic-server.png",
        priority = "high",
        width = 64,
        height = 64,
        frame_count = 1,
        shift = {0, 0},
        scale = 0.5
      },
      {
        filename = sprite_path .. "basic-server-shadow.png",
        priority = "high",
        width = 64,
        height = 64,
        frame_count = 1,
        shift = {0, 0},
        scale = 0.5,
        draw_as_shadow = true
      }
    }
  }
}
data:extend({server})

-- Advanced Server - Clone assembling machine 2
-- Purpose: Higher-tier data processing (2× speed)
-- Unlocked by IT Automation technology
local adv_server = table.deepcopy(data.raw["assembling-machine"]["assembling-machine-2"])
adv_server.name = "advanced-server"
adv_server.icon = "__sysadmin-poc__/graphics/icons/advanced-server.png"
adv_server.icon_size = 32
adv_server.minable.result = "advanced-server"
adv_server.crafting_categories = {"data-processing"}
adv_server.crafting_speed = 2  -- 2× faster than basic
adv_server.energy_usage = "400kW"  -- 2× power
adv_server.localised_name = {"entity-name.advanced-server"}
adv_server.localised_description = {"entity-description.advanced-server"}
adv_server.next_upgrade = "hp-server"
adv_server.fast_replaceable_group = "server"
-- Make it 1x1 instead of 3x3
adv_server.collision_box = {{-0.35, -0.35}, {0.35, 0.35}}
adv_server.selection_box = {{-0.5, -0.5}, {0.5, 0.5}}
adv_server.drawing_box = {{-0.5, -0.5}, {0.5, 0.5}}
-- Remove fluid boxes (pipe connections) - not needed for data processing and incompatible with 1x1 size
adv_server.fluid_boxes = nil
adv_server.fluid_boxes_off_when_no_fluid_recipe = nil
-- Set fixed recipe so it auto-processes data packets
adv_server.fixed_recipe = "process-data"
-- Use custom sprite for the server graphics
adv_server.graphics_set = {
  animation = {
    layers = {
      {
        filename = sprite_path .. "advanced-server.png",
        priority = "high",
        width = 64,
        height = 64,
        frame_count = 1,
        shift = {0, 0},
        scale = 0.5
      },
      {
        filename = sprite_path .. "advanced-server-shadow.png",
        priority = "high",
        width = 64,
        height = 64,
        frame_count = 1,
        shift = {0, 0},
        scale = 0.5,
        draw_as_shadow = true
      }
    }
  }
}
data:extend({adv_server})

-- High-Performance Server - Clone assembling machine 3
-- Purpose: Highest-tier data processing (4× speed)
-- Unlocked by IT Advanced technology
local hp_server = table.deepcopy(data.raw["assembling-machine"]["assembling-machine-3"])
hp_server.name = "hp-server"
hp_server.icon = "__sysadmin-poc__/graphics/icons/hp-server.png"
hp_server.icon_size = 32
hp_server.minable.result = "hp-server"
hp_server.crafting_categories = {"data-processing"}
hp_server.crafting_speed = 4  -- 4× faster than basic
hp_server.energy_usage = "800kW"  -- 4× power
hp_server.localised_name = {"entity-name.hp-server"}
hp_server.localised_description = {"entity-description.hp-server"}
hp_server.next_upgrade = nil
hp_server.fast_replaceable_group = "server"
-- Make it 1x1 instead of 3x3
hp_server.collision_box = {{-0.35, -0.35}, {0.35, 0.35}}
hp_server.selection_box = {{-0.5, -0.5}, {0.5, 0.5}}
hp_server.drawing_box = {{-0.5, -0.5}, {0.5, 0.5}}
-- Remove fluid boxes (pipe connections) - not needed for data processing and incompatible with 1x1 size
hp_server.fluid_boxes = nil
hp_server.fluid_boxes_off_when_no_fluid_recipe = nil
-- Set fixed recipe so it auto-processes data packets
hp_server.fixed_recipe = "process-data"
-- Use custom sprite for the server graphics
hp_server.graphics_set = {
  animation = {
    layers = {
      {
        filename = sprite_path .. "hp-server.png",
        priority = "high",
        width = 64,
        height = 64,
        frame_count = 1,
        shift = {0, 0},
        scale = 0.5
      },
      {
        filename = sprite_path .. "hp-server-shadow.png",
        priority = "high",
        width = 64,
        height = 64,
        frame_count = 1,
        shift = {0, 0},
        scale = 0.5,
        draw_as_shadow = true
      }
    }
  }
}
data:extend({hp_server})

-- Circuit Bridge - Clone constant combinator
-- Purpose: Outputs IT metrics as circuit signals, reads control signals
-- Why combinator: Native circuit network support, can set/read signals programmatically
local bridge = table.deepcopy(data.raw["constant-combinator"]["constant-combinator"])
bridge.name = "circuit-bridge"
bridge.icon = "__sysadmin-poc__/graphics/icons/circuit-bridge.png"
bridge.icon_size = 32
bridge.minable.result = "circuit-bridge"
bridge.localised_name = {"entity-name.circuit-bridge"}
bridge.localised_description = {"entity-description.circuit-bridge"}
-- Use custom sprite
bridge.sprites = {
  north = {
    layers = {
      {
        filename = sprite_path .. "circuit-bridge.png",
        width = 64,
        height = 64,
        shift = {0, 0},
        scale = 0.5
      },
      {
        filename = sprite_path .. "circuit-bridge-shadow.png",
        width = 64,
        height = 64,
        shift = {0, 0},
        scale = 0.5,
        draw_as_shadow = true
      }
    }
  },
  east = {
    layers = {
      {
        filename = sprite_path .. "circuit-bridge.png",
        width = 64,
        height = 64,
        shift = {0, 0},
        scale = 0.5
      },
      {
        filename = sprite_path .. "circuit-bridge-shadow.png",
        width = 64,
        height = 64,
        shift = {0, 0},
        scale = 0.5,
        draw_as_shadow = true
      }
    }
  },
  south = {
    layers = {
      {
        filename = sprite_path .. "circuit-bridge.png",
        width = 64,
        height = 64,
        shift = {0, 0},
        scale = 0.5
      },
      {
        filename = sprite_path .. "circuit-bridge-shadow.png",
        width = 64,
        height = 64,
        shift = {0, 0},
        scale = 0.5,
        draw_as_shadow = true
      }
    }
  },
  west = {
    layers = {
      {
        filename = sprite_path .. "circuit-bridge.png",
        width = 64,
        height = 64,
        shift = {0, 0},
        scale = 0.5
      },
      {
        filename = sprite_path .. "circuit-bridge-shadow.png",
        width = 64,
        height = 64,
        shift = {0, 0},
        scale = 0.5,
        draw_as_shadow = true
      }
    }
  }
}
data:extend({bridge})

-- Dashboard Terminal - Clone programmable speaker
-- Purpose: Displays IT metrics GUI when clicked
-- Why speaker: Has GUI interaction, power requirement, fits "terminal/display" concept
local dashboard = table.deepcopy(data.raw["programmable-speaker"]["programmable-speaker"])
dashboard.name = "dashboard-terminal"
dashboard.icon = "__sysadmin-poc__/graphics/icons/dashboard-terminal.png"
dashboard.icon_size = 32
dashboard.minable.result = "dashboard-terminal"
dashboard.energy_usage_per_tick = "5kW"
dashboard.localised_name = {"entity-name.dashboard-terminal"}
dashboard.localised_description = {"entity-description.dashboard-terminal"}
-- Use custom sprite
dashboard.sprite = {
  layers = {
    {
      filename = sprite_path .. "dashboard-terminal.png",
      width = 64,
      height = 64,
      shift = {0, 0},
      scale = 0.5
    },
    {
      filename = sprite_path .. "dashboard-terminal-shadow.png",
      width = 64,
      height = 64,
      shift = {0, 0},
      scale = 0.5,
      draw_as_shadow = true
    }
  }
}
data:extend({dashboard})
