-- Sysadmin POC - Item Definitions

data:extend({
  -- IT Infrastructure tab in the crafting menu
  {
    type = "item-group",
    name = "it-infrastructure",
    icon = "__sysadmin-poc__/graphics/icons/basic-server.png",
    icon_size = 32,
    order = "z[it-infrastructure]"
  },

  -- Subgroups within the IT tab
  {
    type = "item-subgroup",
    name = "it-data",
    group = "it-infrastructure",
    order = "a[data]"
  },
  {
    type = "item-subgroup",
    name = "it-network",
    group = "it-infrastructure",
    order = "b[network]"
  },
  {
    type = "item-subgroup",
    name = "it-compute",
    group = "it-infrastructure",
    order = "c[compute]"
  },
  {
    type = "item-subgroup",
    name = "it-monitoring",
    group = "it-infrastructure",
    order = "d[monitoring]"
  },

  -- Data Packet - generated by monitored assemblers
  {
    type = "item",
    name = "data-packet",
    icon = "__sysadmin-poc__/graphics/icons/data-packet.png",
    icon_size = 32,
    subgroup = "it-data",
    order = "a[data-packet]",
    stack_size = 1000
  },

  -- Data Sensor - placeable item
  {
    type = "item",
    name = "data-sensor",
    icon = "__sysadmin-poc__/graphics/icons/data-sensor.png",
    icon_size = 32,
    subgroup = "it-data",
    order = "b[data-sensor]",
    stack_size = 50,
    place_result = "data-sensor"
  },

  -- Network Cable - placeable item
  {
    type = "item",
    name = "network-cable",
    icon = "__sysadmin-poc__/graphics/icons/network-cable.png",
    icon_size = 32,
    subgroup = "it-network",
    order = "a[network-cable]",
    stack_size = 100,
    place_result = "network-cable"
  },

  -- Network Cable Underground - placeable item
  {
    type = "item",
    name = "network-cable-underground",
    icon = "__sysadmin-poc__/graphics/icons/network-cable-underground.png",
    icon_size = 32,
    subgroup = "it-network",
    order = "b[network-cable-underground]",
    stack_size = 50,
    place_result = "network-cable-underground"
  },

  -- Network Cable Splitter - placeable item
  {
    type = "item",
    name = "network-cable-splitter",
    icon = "__sysadmin-poc__/graphics/icons/network-cable-splitter.png",
    icon_size = 32,
    subgroup = "it-network",
    order = "c[network-cable-splitter]",
    stack_size = 50,
    place_result = "network-cable-splitter"
  },

  -- Basic Server - placeable item
  {
    type = "item",
    name = "basic-server",
    icon = "__sysadmin-poc__/graphics/icons/basic-server.png",
    icon_size = 32,
    subgroup = "it-compute",
    order = "a[basic-server]",
    stack_size = 20,
    place_result = "basic-server"
  },

  -- Advanced Server - placeable item (tier 2)
  {
    type = "item",
    name = "advanced-server",
    icon = "__sysadmin-poc__/graphics/icons/advanced-server.png",
    icon_size = 32,
    subgroup = "it-compute",
    order = "b[advanced-server]",
    stack_size = 20,
    place_result = "advanced-server"
  },

  -- High-Performance Server - placeable item (tier 3)
  {
    type = "item",
    name = "hp-server",
    icon = "__sysadmin-poc__/graphics/icons/hp-server.png",
    icon_size = 32,
    subgroup = "it-compute",
    order = "c[hp-server]",
    stack_size = 20,
    place_result = "hp-server"
  },

  -- Circuit Bridge - placeable item
  {
    type = "item",
    name = "circuit-bridge",
    icon = "__sysadmin-poc__/graphics/icons/circuit-bridge.png",
    icon_size = 32,
    subgroup = "it-monitoring",
    order = "a[circuit-bridge]",
    stack_size = 50,
    place_result = "circuit-bridge"
  },

  -- Dashboard Terminal - opens IT metrics GUI
  {
    type = "item",
    name = "dashboard-terminal",
    icon = "__sysadmin-poc__/graphics/icons/dashboard-terminal.png",
    icon_size = 32,
    subgroup = "it-monitoring",
    order = "b[dashboard-terminal]",
    stack_size = 20,
    place_result = "dashboard-terminal"
  }
})
